name: Run Python Script

on:
  schedule:
    # Execute de segunda a sexta-feira às 9:00 UTC
    - cron: "0 5 * * 1-5"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Certifique-se de ter um arquivo requirements.txt com todas as dependências

    - name: Run Python script
      run: |
        python seu_script.py
      env:
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        USUARIO: ${{ secrets.USUARIO }}
        SENHA: ${{ secrets.SENHA }}
        MAIL_USER: ${{ secrets.MAIL_USER }}