name: Run Python Script

on:
  schedule:
    # Execute de segunda a sexta-feira às 9:00 UTC
    - cron: "*/5* * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.6

    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x


    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      env:
        USUARIO: ${{ secrets.USUARIO }}
        SENHA: ${{ secrets.SENHA }}
        ANTICAPTCHA_API_KEY: ${{ secrets.ANTICAPTCHA_API_KEY }}
        MAIL_USER: ${{ secrets.MAIL_USER }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
       run: |
         python QS2.py